### PR TITLE
Development

### PR DESCRIPTION
**Pull request by i4seeu**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, good job.
Kindly remove comments and `puts`.
Also, `my_each` and `my_count` isn't working. I got nil for array.my_each { |i| i }
Once fixed, kindly resubmit for review.

**Comment by i4seeu** [comment]
What are the test cases you are using because its working on  my end on the count method that is

**Comment by inhaq** [comment]
> What are the test cases you are using because its working on my end

`my_each`: `[1, 2, 3, 4, 5].my_each { |i| i }`
`my_count`: `[1, 2, 3, 4, 5].my_count`

**Comment by i4seeu** [comment]
ok,

**Review by inhaq — CHANGES_REQUESTED** [review]
`my_count` is still not working. I got `#<Enumerator: 5:each>` for `[1,2,3,4,5].my_count` instead of 5.
Once fixed, kindly resubmit for review.

**Review by inhaq — APPROVED** [review]
Awesome. It's 👍🏻, go ahead and submit your project completion form.
Good luck with the next project 🎉

**Pull request merged**
